default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USER_NAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budget_app_development

test:
  <<: *default
  database: Budget_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
